### ISSUE TITLE
Not working with babeljs 6 (react-native v0.16.x/master)

### ISSUE THREAD

**Issue by Gurpartap** [iodine/react-native-drawer-layout#14]
**.babelrc from DrawyerLayoutExample** (works fine with react-native-0.15.0) :

``` json
{
  "retainLines": true,
  "compact": true,
  "comments": false,
  "whitelist": [
    "es6.constants",
    "es6.arrowFunctions",
    "es6.blockScoping",
    "es6.classes",
    "es6.destructuring",
    "es6.parameters",
    "es6.properties.computed",
    "es6.properties.shorthand",
    "es6.spread",
    "es6.modules",
    "es6.forOf",
    "es6.templateLiterals",
    "es7.trailingFunctionCommas",
    "es7.objectRestSpread",
    "es7.asyncFunctions",
    "es7.classProperties",
    "es7.decorators",
    "es7.doExpressions",
    "flow",
    "react",
    "react.displayName"
  ],
  "sourceMaps": false
}
```

**package.json from my app with react-native-0.16.0-rc/babeljs6** (does not work):

``` json
{
  "name": "projectname",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "babel-plugin-check-es2015-constants": "^6.2.0",
    "babel-plugin-external-helpers-2": "^6.1.4",
    "babel-plugin-syntax-async-functions": "^6.0.14",
    "babel-plugin-syntax-class-properties": "^6.0.14",
    "babel-plugin-syntax-decorators": "^6.1.18",
    "babel-plugin-syntax-flow": "^6.0.14",
    "babel-plugin-syntax-jsx": "^6.0.14",
    "babel-plugin-syntax-trailing-function-commas": "^6.0.14",
    "babel-plugin-transform-class-properties": "^6.0.14",
    "babel-plugin-transform-decorators": "^6.1.18",
    "babel-plugin-transform-do-expressions": "^6.1.18",
    "babel-plugin-transform-es2015-arrow-functions": "^6.0.14",
    "babel-plugin-transform-es2015-block-scoping": "^6.0.18",
    "babel-plugin-transform-es2015-classes": "^6.1.2",
    "babel-plugin-transform-es2015-computed-properties": "^6.0.14",
    "babel-plugin-transform-es2015-constants": "^6.0.15",
    "babel-plugin-transform-es2015-destructuring": "^6.0.18",
    "babel-plugin-transform-es2015-for-of": "^6.1.18",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.1.3",
    "babel-plugin-transform-es2015-parameters": "^6.0.18",
    "babel-plugin-transform-es2015-shorthand-properties": "^6.0.14",
    "babel-plugin-transform-es2015-spread": "^6.0.14",
    "babel-plugin-transform-es2015-template-literals": "^6.0.14",
    "babel-plugin-transform-flow-strip-types": "^6.0.14",
    "babel-plugin-transform-object-assign": "^6.0.14",
    "babel-plugin-transform-object-rest-spread": "^6.0.14",
    "babel-plugin-transform-react-display-name": "^6.0.14",
    "babel-plugin-transform-react-jsx": "^6.0.18",
    "babel-plugin-transform-regenerator": "^6.0.18",
    "react-native": "facebook/react-native",
    "react-native-animatable": "^0.3.1",
    "react-native-button": "^1.3.1",
    "react-native-drawer-layout": "^0.2.1"
  },
  "babel": {
    "retainLines": true,
    "compact": true,
    "comments": false,
    "plugins": [
      "syntax-decorators",
      "transform-decorators",
      "transform-do-expressions",
      "transform-es2015-arrow-functions",
      "transform-es2015-block-scoping",
      "transform-es2015-classes",
      "transform-es2015-computed-properties",
      "transform-es2015-destructuring",
      "transform-es2015-for-of",
      "transform-es2015-modules-commonjs",
      "transform-es2015-parameters",
      "transform-es2015-shorthand-properties",
      "transform-es2015-spread",
      "transform-es2015-template-literals",
      "transform-object-rest-spread",
      "transform-react-display-name",
      "transform-react-jsx",
      "check-es2015-constants",
      "syntax-async-functions",
      "syntax-flow",
      "syntax-trailing-function-commas",
      "syntax-class-properties"
    ],
    "sourceMaps": false
  }
}
```

![screen shot 2015-11-29 at 3 02 04 am](https://cloud.githubusercontent.com/assets/39792/11454130/ce22d8fc-9648-11e5-92b3-2551b919933f.png)

I've been told on slack that babeljs 6 does not support decorators at the moment as they're anticipating stability in the decorators spec.

I suppose, going forward, DrawerLayout will need some work before rn-v0.16.0 is released. Or is there another way out of this?

**Comment by DanielMSchmidt** [comment]
To my mind DrawerLayout should not be this dependent on the babel plugins / versions used in RN. Wouldn't a build step bring a lot of independency? 

For this to work we would need to 
- have the including of the iOS implementation done like before, only referencing a build version, with decorator and maybe class transformator run on it.
- have a build system, which runs babel to transform such a version
- optionally have travis do and commit these builds, so no one has to remember them manually

The benefit would be having this library without the need to enhance the .babelrc. Some developers may be scared away by the need of including transformations just to use one package. 

What are your thoughts on this @Gurpartap?

**Comment by DanielMSchmidt** [comment]
@Gurpartap Would there be any chance that you may provide a RN 0.16 application, which uses this lib? It would great if you would contribute it as an example application, sothat we have an updated example (current one is on 0.13) and figure this problem out quickly.

**Comment by Gurpartap** [comment]
@DanielMSchmidt It'll be a feat to employ a build system keeping the end developer of the package oblivious of the fact and their project unaffected. And it looks like 319aa80 has already unlocked the achievement.

My experience with es6, babeljs, et al. at this point is fatuous. You can say I was afraid of revealing so. I'll send an example right away for reparation. 🙂

**Comment by onchainguy-btc** [comment]
I was running into this issue, too. Since the merge of #21 I get a different error. The `whitelist` option was removed in babel 6. When I simply remove the `whitelist` part from the `package.json` of this module everything works fine.

**Comment by DanielMSchmidt** [comment]
@seb0zz This should be fixed on master, did you experience it with the 0.2 version? If you try master it should work, as we compile a es5 version.

**Comment by onchainguy-btc** [comment]
I am working with master, this is the error message:

```
uncaught error Error: ReferenceError: [BABEL] /Users/MyUser/MyReactProject/node_modules/react-native-drawer-layout/dist/index.js: Unknown option: /Users/MyUser/MyReactProject/node_modules/react-native-drawer-layout/package.json.whitelist
```

**Comment by DanielMSchmidt** [comment]
Okay, i am not sure why. I will investigate and share the result with you guys. Your project is simply react-native init ?

**Comment by onchainguy-btc** [comment]
Yes right, should be very simple to set up. Just react native init, install drawer and then build -> run into error

**Comment by Gurpartap** [comment]
And `npm install autowind-decorator --save`.

The server runs for me but Xcode fails to compile with the same error as @seb0zz. 

``` sh
+ DEST=/Users/Gurpartap/Library/Developer/Xcode/DerivedData/DrawerLayoutExample-ekxyecxxssyiaxbydczmxjndytwr/Build/Products/Debug-iphonesimulator/DrawerLayoutExample.app
+ '[' -z '' ']'
+ export NVM_DIR=/Users/Gurpartap/.nvm
+ NVM_DIR=/Users/Gurpartap/.nvm
+ [[ -s /Users/Gurpartap/.nvm/nvm.sh ]]
++ command -v brew
+ [[ -x /usr/local/bin/brew ]]
++ brew --prefix nvm
+ [[ -s /usr/local/Cellar/nvm/0.29.0/nvm.sh ]]
+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/Gurpartap/Library/Developer/Xcode/DerivedData/DrawerLayoutExample-ekxyecxxssyiaxbydczmxjndytwr/Build/Products/Debug-iphonesimulator/DrawerLayoutExample.app/main.jsbundle --assets-dest /Users/Gurpartap/Library/Developer/Xcode/DerivedData/DrawerLayoutExample-ekxyecxxssyiaxbydczmxjndytwr/Build/Products/Debug-iphonesimulator/DrawerLayoutExample.app
bundle: Created ReactPackager
uncaught error Error: ReferenceError: [BABEL] /Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/react-native-drawer-layout/dist/index.js: Unknown option: /Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/react-native-drawer-layout/package.json.whitelist
    at Logger.error (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:30)
    at OptionManager.init (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transform (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/react-native/packager/transformer.js:56:24)
TransformError: /Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/react-native-drawer-layout/dist/index.js: [BABEL] /Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/react-native-drawer-layout/dist/index.js: Unknown option: /Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/react-native-drawer-layout/package.json.whitelist
See logs /var/folders/8b/_lwl7spn5qz9d2t35gy3q1p00000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/bser/index.js:289:10)
    at /Users/Gurpartap/Projects/Github/Gurpartap/DrawerLayoutExample/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
Command /bin/sh failed with exit code 1
```

Android app compiles, runs and complains, "Did you forget to start development server or connect your device?"

**Comment by DanielMSchmidt** [comment]
Okay, that sucks, I am going to investigate this later today or tomorrow. Maybe we will just remove the whitelist section from the package.json and define the babel transformators in our build step just in that command, should be easier, although maybe harder to maintain. I will let you know as soon as I found a solution
